export const RUBROS = [
  { value: 'albanil', label: 'Albañil' },
  { value: 'electricista', label: 'Electricista' },
  { value: 'plomero_gasista', label: 'Plomero / Gasista' },
  { value: 'carpintero', label: 'Carpintero' },
  { value: 'pintor', label: 'Pintor' },
  { value: 'herrero', label: 'Herrero' },
  { value: 'soldador', label: 'Soldador' },
  { value: 'techista', label: 'Techista' },
  { value: 'cerrajero', label: 'Cerrajero' },
  { value: 'mecanico_automotor', label: 'Mecánico automotor' },
  { value: 'gomeria', label: 'Gomería' },
  { value: 'chapista_pintor', label: 'Chapista y pintor automotor' },
  { value: 'refrigeracion_ac', label: 'Refrigeración y aire acondicionado' },
  { value: 'camaras_seguridad', label: 'Instalador de cámaras de seguridad' },
  { value: 'redes_fibra', label: 'Instalador de redes y fibra óptica' },
  { value: 'jardinero', label: 'Jardinero / Parquista' },
  { value: 'fumigador', label: 'Fumigador' },
  { value: 'yesero', label: 'Yesero' },
  { value: 'ceramicos', label: 'Colocador de cerámicos y porcelanato' },
  { value: 'vidriero', label: 'Vidriero' },
  { value: 'tapicero', label: 'Tapicero' },
  { value: 'costurero', label: 'Costurero / Modista' },
  { value: 'peluquero', label: 'Peluquero / Barbero' },
  { value: 'estetica', label: 'Manicura y estética' },
  { value: 'cocinero', label: 'Cocinero' },
  { value: 'panadero', label: 'Panadero' },
  { value: 'pastelero', label: 'Pastelero' },
  { value: 'carpintero_metalico', label: 'Carpintero metálico' },
  { value: 'tornero', label: 'Tornero' },
  { value: 'electricista_industrial', label: 'Electricista industrial' },
  { value: 'maquinaria_pesada', label: 'Operador de maquinaria pesada' },
  { value: 'tecnico_computacion', label: 'Técnico en computación' },
  { value: 'reparador_celulares', label: 'Reparador de celulares' },
  { value: 'fotografo', label: 'Fotógrafo' },
  { value: 'herrero_artesanal', label: 'Herrero artesanal' },
]

export const RUBRO_COLORES = {
  albanil: { bg: '#eafaf1', color: '#1e8449' },
  electricista: { bg: '#fef9e7', color: '#b7950b' },
  plomero_gasista: { bg: '#e8f4fd', color: '#1a6fa8' },
  carpintero: { bg: '#fdebd0', color: '#ca6f1e' },
  pintor: { bg: '#f4ecf7', color: '#7d3c98' },
  herrero: { bg: '#f2f3f4', color: '#5d6d7e' },
  soldador: { bg: '#fdfefe', color: '#717d7e' },
  techista: { bg: '#fef5e7', color: '#d68910' },
  cerrajero: { bg: '#eaf2ff', color: '#1a5276' },
  mecanico_automotor: { bg: '#f4ecf7', color: '#6c3483' },
  gomeria: { bg: '#f2f3f4', color: '#4d5656' },
  chapista_pintor: { bg: '#fdebd0', color: '#935116' },
  refrigeracion_ac: { bg: '#e8f8f5', color: '#0e6655' },
  camaras_seguridad: { bg: '#eaecee', color: '#2e4057' },
  redes_fibra: { bg: '#e8f4fd', color: '#154360' },
  jardinero: { bg: '#eafaf1', color: '#145a32' },
  fumigador: { bg: '#fdedec', color: '#922b21' },
  yesero: { bg: '#fdfefe', color: '#626567' },
  ceramicos: { bg: '#fef9e7', color: '#9a7d0a' },
  vidriero: { bg: '#e8f8f5', color: '#117a65' },
  tapicero: { bg: '#f9ebea', color: '#922b21' },
  costurero: { bg: '#f4ecf7', color: '#76448a' },
  peluquero: { bg: '#fef9e7', color: '#9a7d0a' },
  estetica: { bg: '#fdedec', color: '#c0392b' },
  cocinero: { bg: '#fdebd0', color: '#a04000' },
  panadero: { bg: '#fef5e7', color: '#b7770d' },
  pastelero: { bg: '#fef5e7', color: '#cb4335' },
  carpintero_metalico: { bg: '#f2f3f4', color: '#5d6d7e' },
  tornero: { bg: '#eaecee', color: '#4d5656' },
  electricista_industrial: { bg: '#fef9e7', color: '#7d6608' },
  maquinaria_pesada: { bg: '#f2f3f4', color: '#2e4057' },
  tecnico_computacion: { bg: '#e8f4fd', color: '#1f618d' },
  reparador_celulares: { bg: '#eaf2ff', color: '#1a5276' },
  fotografo: { bg: '#f9ebea', color: '#78281f' },
  herrero_artesanal: { bg: '#f2f3f4', color: '#4a235a' },
}

export function getRubroLabel(value) {
  return RUBROS.find(r => r.value === value)?.label || value
}

export function getRubroColor(value) {
  return RUBRO_COLORES[value] || { bg: '#f0f0f0', color: '#555' }
}